/** @typedef {import('../src/types/repair.js').Repair} Repair */

/** @type {Repair[]} */
export const seedRepairs = [
  {
    id: "GR-2401",
    unit: "B204",
    building: "Genesis",
    title: "Leaking kitchen tap",
    description: "Water dripping under sink; resident reported damp cupboard.",
    category: "plumbing",
    status: "in_progress",
    priority: "medium",
    reportedAt: "2026-05-28T09:15:00.000Z",
    reportedBy: "Thabo M.",
    assignedTo: "Sipho N.",
    scheduledFor: "2026-06-05",
    estimated_cost: 850,
    actual_cost: 620,
  },
  {
    id: "GR-2402",
    unit: "A112",
    building: "Lascelles",
    title: "Bedroom light not working",
    description: "Ceiling fitting flickers then goes off. Possible wiring fault.",
    category: "electrical",
    status: "open",
    priority: "high",
    reportedAt: "2026-06-01T14:30:00.000Z",
    reportedBy: "Lerato K.",
    estimated_cost: 1200,
  },
  {
    id: "GR-2403",
    unit: "T308",
    building: "Truman House",
    title: "Broken wardrobe door",
    description: "Hinge snapped; door hanging loose and unsafe.",
    category: "appliance",
    status: "awaiting_parts",
    priority: "low",
    reportedAt: "2026-05-20T11:00:00.000Z",
    reportedBy: "James P.",
    assignedTo: "James M.",
    scheduledFor: "2026-06-06",
    estimated_cost: 450,
  },
  {
    id: "GR-2404",
    unit: "C101",
    building: "Claim Street Main",
    title: "Blocked shower drain",
    description: "Water pooling in shower tray; slow drainage over 3 days.",
    category: "plumbing",
    status: "completed",
    priority: "medium",
    reportedAt: "2026-05-15T08:00:00.000Z",
    completedAt: "2026-05-18T16:30:00.000Z",
    reportedBy: "Nomsa D.",
    assignedTo: "Sipho N.",
    scheduledFor: "2026-05-17",
    estimated_cost: 600,
    actual_cost: 580,
  },
  {
    id: "GR-2405",
    unit: "B310",
    building: "Genesis",
    title: "Aircon not cooling",
    description: "Unit blows warm air only; filter may need replacement.",
    category: "hvac",
    status: "open",
    priority: "urgent",
    reportedAt: "2026-06-04T07:45:00.000Z",
    reportedBy: "David R.",
    estimated_cost: 2500,
  },
  {
    id: "GR-2406",
    unit: "L205",
    building: "Lascelles",
    title: "Cracked window pane",
    description: "Small crack spreading on exterior-facing bedroom window.",
    category: "structural",
    status: "in_progress",
    priority: "high",
    reportedAt: "2026-05-30T10:20:00.000Z",
    reportedBy: "Zanele T.",
    assignedTo: "Given K.",
    scheduledFor: "2026-06-05",
    estimated_cost: 3200,
  },
  {
    id: "GR-2407",
    unit: "T102",
    building: "Truman House",
    title: "Stove burner faulty",
    description: "Front-left burner won't ignite; smell of gas when turned on.",
    category: "appliance",
    status: "cancelled",
    priority: "urgent",
    reportedAt: "2026-05-10T18:00:00.000Z",
    reportedBy: "Michael S.",
    estimated_cost: 1800,
  },
  {
    id: "GR-2408",
    unit: "CS412",
    building: "Claim Street Main",
    title: "Paint peeling in bathroom",
    description: "Moisture damage above shower; mould spots visible.",
    category: "painting",
    status: "open",
    priority: "low",
    reportedAt: "2026-06-02T12:00:00.000Z",
    reportedBy: "Ayanda M.",
    estimated_cost: 950,
  },
  {
    id: "GR-2409",
    unit: "G118",
    building: "Genesis",
    title: "Cockroach infestation",
    description: "Multiple sightings in kitchen area over past week.",
    category: "pest_control",
    status: "in_progress",
    priority: "medium",
    reportedAt: "2026-06-03T09:00:00.000Z",
    reportedBy: "Precious L.",
    assignedTo: "PestShield SA",
    scheduledFor: "2026-06-05",
    estimated_cost: 700,
  },
  {
    id: "GR-2410",
    unit: "L401",
    building: "Lascelles",
    title: "Door lock jammed",
    description: "Main entrance lock stiff; key difficult to turn.",
    category: "structural",
    status: "completed",
    priority: "high",
    reportedAt: "2026-05-22T15:30:00.000Z",
    completedAt: "2026-05-24T11:00:00.000Z",
    reportedBy: "Chris V.",
    assignedTo: "Sipho N.",
    scheduledFor: "2026-05-23",
    estimated_cost: 400,
    actual_cost: 350,
  },
];
